# Generated by Django 5.0.6 on 2024-09-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
