# Generated by Django 5.0.6 on 2024-09-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_room_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='busy',
        ),
    ]
