# Generated by Django 5.0.6 on 2024-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_room_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='filter',
            field=models.CharField(choices=[('За зростанням', 'increase'), ('За спаданням', 'decrease')], default='increase', max_length=23),
        ),
    ]
