# Generated by Django 5.0.6 on 2024-09-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_room_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='filter',
        ),
    ]
