# Generated by Django 5.0.6 on 2024-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_room_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='filter',
            field=models.CharField(choices=[('increase', 'increase'), ('decrease', 'decrease')], default='increase', max_length=23),
        ),
    ]
