# Generated by Django 5.0.6 on 2024-09-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='filter',
            field=models.CharField(choices=[('increase', 'За зростанням'), ('decrease', 'За спаданням')], default='increase', max_length=23),
        ),
    ]
